# Generated by Django 2.0.3 on 2018-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbase', '0002_post_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='global_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='local_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='quality',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='scenario',
            field=models.BooleanField(),
        ),
    ]
