# Generated by Django 2.0.3 on 2018-03-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbase', '0004_auto_20180322_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
